# Generated by Django 2.2.dev20180917194117 on 2018-09-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('repository', models.CharField(max_length=300)),
                ('path', models.CharField(max_length=1000)),
            ],
        ),
    ]
