# Generated by Django 2.2.dev20180917194117 on 2018-09-25 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_testing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='GithubFile',
        ),
    ]
